[package]
name = "abc170"
version = "0.1.0"
authors = ["Yuma Ishikawa <yuma.fuu05@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = {version = "=0.3.4", features = ["derive"]}

[profile.release]
lto = true
panic = 'abort'
